/*
 * BUTTON_cfg.h
 *
 * Created: 6/11/2023 9:29:32 AM
 *  Author: ESRAA_ABDELNABE
 */ 


#ifndef BUTTON_CFG_H_
#define BUTTON_CFG_H_

/*
#define LED_BUTTON1_PORT  DIO_PORTD
#define LED_BUTTON1_PIN  DIO_PIN7
#define LED_BUTTON1_CONNECTION  PULL_UP

#define LED_BUTTON2_PORT  DIO_PORTD
#define LED_BUTTON2_PIN  DIO_PIN6
#define LED_BUTTON2_CONNECTION  PULL_UP

#define LED_BUTTON3_PORT  DIO_PORTD
#define LED_BUTTON3_PIN  DIO_PIN5
#define LED_BUTTON3_CONNECTION  PULL_UP

#define LED_BUTTON4_PORT  DIO_PORTD
#define LED_BUTTON4_PIN  DIO_PIN4
#define LED_BUTTON4_CONNECTION  PULL_UP
*/


#endif /* BUTTON_CFG_H_ */